export const actionTypes = {
  REQUEST_WORKOUTS: "REQUEST_WORKOUTS",
  RECEIVE_WORKOUTS: "RECEIVE_WORKOUTS",
  SAVING_WORKOUT: "SAVING_WORKOUT",
  SAVING_WORKOUT_DONE: "SAVING_WORKOUT_DONE",
  WORKOUTS_FETCH_FAILURE: "WORKOUTS_FETCH_FAILURE",
}